# Generated by Django 5.1.6 on 2026-04-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_instructorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_1', models.CharField(blank=True, max_length=255, null=True)),
                ('text_2', models.CharField(blank=True, max_length=255, null=True)),
                ('text_3', models.CharField(blank=True, max_length=255, null=True)),
                ('experience', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='mini_lms/images/')),
                ('company_image_1', models.FileField(blank=True, null=True, upload_to='mini_lms/images/')),
                ('company_image_2', models.FileField(blank=True, null=True, upload_to='mini_lms/images/')),
                ('visible', models.IntegerField(default=1)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Instructor Profile',
                'verbose_name_plural': 'Instructor Profile',
                'managed': False,
            },
        ),
    ]
