# Generated by Django 5.1.6 on 2026-04-16 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_instructorprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstructorProfile',
        ),
    ]
