# Generated by Django 5.1.6 on 2026-04-16 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_instructorprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='restored_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='transaction_id',
        ),
    ]
