# Generated by Django 5.1.6 on 2026-07-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('USER_LOGIN', 'User Logged In'), ('USER_LOGOUT', 'User Logged Out'), ('COURSE_STARTED', 'Course Started'), ('COURSE_COMPLETED', 'Course Completed'), ('LESSON_STARTED', 'Lesson Started'), ('LESSON_COMPLETED', 'Lesson Completed'), ('NOTE_CREATED', 'Note Created'), ('PROGRESS', 'Progress'), ('CERTIFICATE_GENERATED', 'Certificate Generated')], db_index=True, max_length=50),
        ),
    ]
