# Generated by Django 5.1.6 on 2026-07-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('USER_LOGIN', 'User Logged In'), ('USER_LOGOUT', 'User Logged Out'), ('PROFILE_UPDATED', 'Profile Updated'), ('COURSE_STARTED', 'Course Started'), ('COURSE_COMPLETED', 'Course Completed'), ('LESSON_STARTED', 'Lesson Started'), ('LESSON_COMPLETED', 'Lesson Completed'), ('QUIZ_STARTED', 'Quiz Started'), ('QUIZ_COMPLETED', 'Quiz Completed'), ('NOTE_CREATED', 'Note Created'), ('NOTE_UPDATED', 'Note Updated'), ('NOTE_DELETED', 'Note Deleted'), ('PROGRESS', 'Progress'), ('CERTIFICATE_GENERATED', 'Certificate Generated')], db_index=True, max_length=50),
        ),
    ]
