# Generated by Django 5.1.6 on 2026-06-29 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_coupon_minimum_cart_value'),
        ('questions', '0002_chapterquizs_quizquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterquizs',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.chapters'),
        ),
    ]
