# Generated by Django 5.1.6 on 2026-06-30 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_coupon_minimum_cart_value'),
        ('questions', '0003_chapterquizs_chapter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_question', models.IntegerField(blank=True, default=0, null=True)),
                ('total_mcq', models.IntegerField(blank=True, default=0, null=True)),
                ('total_right_answer_given', models.IntegerField(blank=True, default=0, null=True)),
                ('total_wrong_answer_given', models.IntegerField(blank=True, default=0, null=True)),
                ('total_never_attempt_question', models.IntegerField(blank=True, default=0, null=True)),
                ('total_flag_marked', models.IntegerField(blank=True, default=0, null=True)),
                ('total_time_taken', models.IntegerField(blank=True, default=0, null=True)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('avg_time_per_question', models.IntegerField(blank=True, default=0, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.chapters')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.chapterquizs')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Practice Tests',
                'verbose_name_plural': 'Practice Tests',
            },
        ),
        migrations.CreateModel(
            name='PracticeTestQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(blank=True, default=0, null=True)),
                ('guess_marked', models.BooleanField(default=False)),
                ('attempted', models.BooleanField(default=False)),
                ('time_taken', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.testquestions')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.questionoptions')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('practice_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.practicetests')),
            ],
            options={
                'verbose_name': 'Practice Test Questions',
                'verbose_name_plural': 'Practice Test Questions',
            },
        ),
    ]
