# Generated by Django 5.1.6 on 2026-07-09 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_practicetests_practicetestquestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicetests',
            name='total_mcq',
        ),
    ]
