# Generated by Django 5.1.6 on 2026-02-23 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0010_remove_instructorprofile_user_and_more'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_question', models.IntegerField(blank=True, default=0, null=True)),
                ('total_right_answer_given', models.IntegerField(blank=True, default=0, null=True)),
                ('total_wrong_answer_given', models.IntegerField(blank=True, default=0, null=True)),
                ('total_never_attempt_question', models.IntegerField(blank=True, default=0, null=True)),
                ('total_flag_marked', models.IntegerField(blank=True, default=0, null=True)),
                ('total_time_taken', models.IntegerField(blank=True, default=0, null=True)),
                ('avg_time_per_question', models.IntegerField(blank=True, default=0, null=True)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assessment Tests',
                'verbose_name_plural': 'Assessment Tests',
            },
        ),
        migrations.CreateModel(
            name='AssessmentTestQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.IntegerField(choices=[(1, 'MCQ')], default=1)),
                ('result', models.BooleanField(default=False)),
                ('attempted', models.BooleanField(default=False)),
                ('guess_marked', models.BooleanField(default=False)),
                ('time_taken', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coursechapters')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.testquestions')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.questionoptions')),
                ('assessment_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.assessmenttests')),
            ],
            options={
                'verbose_name': 'Assessment Attempt Questions',
                'verbose_name_plural': 'Assessment Attempt Questions',
            },
        ),
    ]
