# Generated by Django 5.1.6 on 2026-04-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_study', '0004_instructorpublicprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstructorPublicProfile',
        ),
    ]
