# Generated by Django 5.1.6 on 2026-04-23 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_categories_deleted_at_categories_restored_at_and_more'),
        ('user_study', '0005_delete_instructorpublicprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlectureprogress',
            old_name='lecture_chapter_id',
            new_name='chapter_lecture',
        ),
        migrations.AddField(
            model_name='userlectureprogress',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.videos'),
        ),
    ]
