# Generated by Django 5.1.6 on 2026-04-27 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_study', '0006_rename_lecture_chapter_id_userlectureprogress_chapter_lecture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='chapter_video',
            new_name='chapter_lecture',
        ),
    ]
