# Generated by Django 5.1.6 on 2026-04-29 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_study', '0007_rename_chapter_video_notes_chapter_lecture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotional', models.BooleanField(default=False)),
                ('announcements', models.BooleanField(default=False)),
                ('reminders', models.BooleanField(default=False)),
                ('instructor_notification', models.BooleanField(default=False)),
                ('new_login', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Notification Setting',
                'verbose_name_plural': 'User Notification Setting',
            },
        ),
    ]
