# Generated by Django 5.1.6 on 2026-04-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_study', '0008_usernotificationsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotifications',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
