# Generated by Django 5.1.6 on 2026-05-12 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_courseannouncements_announcementcomments'),
        ('user_study', '0009_usernotifications_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotifications',
            name='announcement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.courseannouncements'),
        ),
    ]
