# Generated by Django 5.1.6 on 2026-05-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_study', '0011_learningreminders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningreminders',
            name='days',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
