# Generated by Django 5.1.6 on 2026-02-23 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_trailuser_trailusercourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='coupon',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='subscription.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.coupon'),
        ),
        migrations.AddField(
            model_name='usercourses',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercourses',
            name='expired_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercourses',
            name='progress_percentage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
