# Generated by Django 5.1.6 on 2026-04-20 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_historicalorder_coupon_order_coupon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsettings',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
        migrations.DeleteModel(
            name='HistoricalSettings',
        ),
    ]
