# Generated by Django 5.1.6 on 2026-04-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_remove_historicalsettings_history_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='orderID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='orderID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
