# Generated by Django 5.1.6 on 2026-04-20 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_historicalorder_orderid_order_orderid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalorder',
            old_name='order_payment_id',
            new_name='razorpay_order_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_payment_id',
            new_name='razorpay_order_id',
        ),
    ]
