# Generated by Django 5.1.6 on 2026-04-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0009_rename_order_payment_id_historicalorder_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourses',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
