# Generated by Django 5.1.6 on 2026-04-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_usercourses_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
    ]
