# Generated by Django 5.1.6 on 2026-06-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0011_historicalorder_ispaid_order_ispaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourses',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
