# Generated by Django 5.1.6 on 2026-06-24 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_rename_active_coupon_status'),
        ('subscription', '0012_usercourses_is_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='coupon',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.coupon'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coupon'),
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
