# Generated by Django 5.1.6 on 2026-07-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0013_alter_historicalorder_coupon_alter_order_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'Course'), (2, 'Subscription')], default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'Course'), (2, 'Subscription')], default=1),
        ),
    ]
