# Generated by Django 5.1.6 on 2026-07-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0014_historicalorder_payment_type_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalordersubscriptionpayments',
            name='response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordersubscriptionpayments',
            name='response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
