# Generated by Django 5.1.6 on 2026-07-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0015_historicalordersubscriptionpayments_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
