# Generated by Django 5.1.6 on 2026-04-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_faqtopic_faqs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.IntegerField(choices=[(1, 'Test Mode'), (2, 'Live Mode')], default=1)),
                ('test_public_key', models.CharField(blank=True, max_length=255, null=True)),
                ('test_secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('live_public_key', models.CharField(blank=True, max_length=255, null=True)),
                ('live_secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('no_days_trail', models.IntegerField(blank=True, default=7, null=True)),
                ('try_for_free', models.IntegerField(blank=True, default=30, null=True)),
                ('allow_device_restriction', models.BooleanField(default=False)),
                ('allowed_desktop', models.IntegerField(blank=True, default=1, null=True)),
                ('allowed_tablet', models.IntegerField(blank=True, default=1, null=True)),
                ('allowed_phone', models.IntegerField(blank=True, default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
