# Generated by Django 5.1.6 on 2026-04-20 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='GeneralSettings',
        ),
        migrations.AlterModelOptions(
            name='generalsettings',
            options={'verbose_name': 'General Settings', 'verbose_name_plural': 'General Settings'},
        ),
    ]
