# Generated by Django 5.1.6 on 2026-05-12 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='attach_file',
        ),
    ]
