# Generated by Django 5.1.6 on 2026-06-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_blog_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
