# Generated by Django 5.1.6 on 2026-06-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_blogcomment_updated_at_alter_blogcomment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
