# Generated by Django 5.1.6 on 2026-06-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_alter_blog_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
