# Generated by Django 5.1.6 on 2026-06-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_rename_name_blogcomment_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('page_type', models.CharField(choices=[('privacy_policy', 'privacy_policy'), ('about_us', 'about_us'), ('terms_conditions', 'terms_conditions')], default='privacy_policy', max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keys', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CMS Pages',
                'verbose_name_plural': 'CMS Pages',
            },
        ),
    ]
