# Generated by Django 5.1.6 on 2026-06-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_cmspages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='testimonials_type',
            field=models.IntegerField(choices=[(1, 'Placement'), (2, 'Institutions'), (3, 'Corporate'), (4, 'Student')], default=4),
        ),
    ]
