# Generated by Django 5.1.6 on 2026-06-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_alter_testimonials_testimonials_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='visible',
        ),
        migrations.AddField(
            model_name='testimonials',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
