# Generated by Django 5.1.6 on 2026-06-09 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_remove_testimonials_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerimages',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='partnerimages',
            name='restored_at',
        ),
        migrations.RemoveField(
            model_name='partnerimages',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='restored_at',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='transaction_id',
        ),
    ]
