# Generated by Django 5.1.6 on 2026-06-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_helpsupporttopics_helpsupportsubtopics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('highest_qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('current_employment_status', models.CharField(choices=[('student', 'Student'), ('fresher', 'Fresher'), ('self_employed', 'Self-Employed'), ('working_professional', 'Working Professional')], default='student', max_length=30)),
                ('total_years_of_experience', models.CharField(choices=[('0-1', '0-1 Year'), ('1-3', '1-3 Years'), ('3-5', '3-5 Years'), ('5+', '5+ Years')], default='0-1', max_length=10)),
                ('role_applying_for', models.CharField(choices=[('academic', 'Academic / Training'), ('sales_marketing', 'Sales & Marketing'), ('operations', 'Operations'), ('tech_it', 'Technology / IT'), ('content_design', 'Content / Design'), ('other', 'Other (Please specify)')], default='academic', max_length=30)),
                ('other_role_specification', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('linkedin_portfolio', models.URLField(blank=True, max_length=500, null=True)),
                ('notice_period', models.CharField(choices=[('immediate', 'Immediate'), ('15_days', '15 Days'), ('30_days', '30 Days'), ('more_than_30', 'More than 30 Days')], default='immediate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Applications',
                'verbose_name_plural': 'Job Applications',
            },
        ),
    ]
