# Generated by Django 5.1.6 on 2026-06-25 07:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_jobapplications'),
        ('courses', '0030_rename_active_coupon_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalBannerCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal name, e.g., Summer Sale 2026', max_length=100)),
                ('display_text', models.CharField(help_text='e.g., Summer Sale is On!', max_length=255)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(help_text='The exact date/time when the countdown hits zero')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupons', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.coupon')),
            ],
            options={
                'verbose_name': 'Promotional Banner Campaign',
                'verbose_name_plural': 'Promotional Banner Campaign',
            },
        ),
    ]
