# Generated by Django 5.1.6 on 2026-06-26 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_promotionalbannercampaign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotionalbannercampaign',
            old_name='is_active',
            new_name='status',
        ),
    ]
