# Generated by Django 5.1.6 on 2026-07-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_rename_is_active_promotionalbannercampaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionalbannercampaign',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='mini_lms/images/'),
        ),
        migrations.AlterField(
            model_name='promotionalbannercampaign',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
