# Generated by Django 5.1.6 on 2026-08-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_communitycategories_communityposts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
