# Generated by Django 5.1.6 on 2026-08-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_generalsettings_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityposts',
            name='total_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communityposts',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communityposts',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
    ]
