# Generated by Django 5.1.6 on 2026-08-11 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_communityposts_total_comments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityposts',
            options={'verbose_name': 'Community Posts', 'verbose_name_plural': 'Community Posts'},
        ),
    ]
