# Generated by Django 5.1.6 on 2026-08-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_alter_communityposts_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypostcomments',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
