# Generated by Django 5.1.6 on 2026-08-11 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_communitypostlikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypostlikes',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.communitypostcomments'),
        ),
    ]
