# Generated by Django 5.1.6 on 2026-08-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_communitypostlikes_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_type', models.CharField(choices=[('authorized_training_partner', 'Authorized Training Partner'), ('business_associate', 'Business Associate'), ('instructor', 'Instructor'), ('corporate_partner', 'Corporate Partner'), ('institutional_partner', 'Institutional Partner'), ('Student_ambassador', 'Student Ambassador')], default='student', max_length=30)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='document/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner Requests',
                'verbose_name_plural': 'Partner Requests',
            },
        ),
    ]
