# Generated by Django 5.1.6 on 2026-09-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_smtpconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewaySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.IntegerField(choices=[(1, 'Test Mode'), (2, 'Live Mode')], default=1)),
                ('test_public_key', models.CharField(blank=True, max_length=255, null=True)),
                ('test_secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('live_public_key', models.CharField(blank=True, max_length=255, null=True)),
                ('live_secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway Setting',
                'verbose_name_plural': 'Payment Gateway Setting',
            },
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='live_public_key',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='live_secret_key',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='test_public_key',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='test_secret_key',
        ),
    ]
