# Generated by Django 5.1.6 on 2026-04-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorprofile',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='instructorprofile',
            name='restored_at',
        ),
        migrations.RemoveField(
            model_name='instructorprofile',
            name='transaction_id',
        ),
    ]
