# Generated by Django 5.1.6 on 2026-01-20 06:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_frequentlyboughtcourse_instructor_courseinstructors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instructor',
            new_name='Instructors',
        ),
    ]
