# Generated by Django 5.1.6 on 2026-01-20 07:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_instructor_instructors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instructors',
            new_name='InstructorProfile',
        ),
        migrations.AlterModelOptions(
            name='instructorprofile',
            options={'verbose_name': 'Instructor Profile', 'verbose_name_plural': 'Instructor Profile'},
        ),
    ]
