# Generated by Django 5.1.6 on 2026-02-19 09:57

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_historicaltrailcourses_trailcourses_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaptertopics',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='chaptertopics',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='historicalchaptertopics',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='historicalchaptertopics',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalchaptertopics',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='historicaltopics',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltopicvideos',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='historicaltopicvideos',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltopicvideos',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='historicaltopicvideos',
            name='video',
        ),
        migrations.RemoveField(
            model_name='topicvideos',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topicvideos',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='topicvideos',
            name='video',
        ),
        migrations.RemoveField(
            model_name='chapters',
            name='chapter_type',
        ),
        migrations.RemoveField(
            model_name='chapters',
            name='no_of_simulations',
        ),
        migrations.RemoveField(
            model_name='chapters',
            name='no_of_topic_videos',
        ),
        migrations.RemoveField(
            model_name='historicalchapters',
            name='chapter_type',
        ),
        migrations.RemoveField(
            model_name='historicalchapters',
            name='no_of_simulations',
        ),
        migrations.RemoveField(
            model_name='historicalchapters',
            name='no_of_topic_videos',
        ),
        migrations.CreateModel(
            name='ChapterLectures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('lecture_type', models.IntegerField(choices=[(1, 'Video'), (2, 'Ebook')], default=1)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.chapters')),
                ('ebook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.chapterbooks')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.videos')),
            ],
            options={
                'verbose_name': 'Chapters Lectures',
                'verbose_name_plural': 'Chapters Lectures',
            },
        ),
        migrations.CreateModel(
            name='HistoricalChapterLectures',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('lecture_type', models.IntegerField(choices=[(1, 'Video'), (2, 'Ebook')], default=1)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('chapter', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.chapters')),
                ('ebook', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.chapterbooks')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.videos')),
            ],
            options={
                'verbose_name': 'historical Chapters Lectures',
                'verbose_name_plural': 'historical Chapters Lectures',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
