# Generated by Django 5.1.6 on 2026-02-19 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_chaptertopics_chapter_and_more'),
        ('user_study', '0002_remove_userwatchedtopicvideos_chapter_topic_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChapterTopics',
        ),
        migrations.DeleteModel(
            name='HistoricalChapterTopics',
        ),
        migrations.DeleteModel(
            name='HistoricalTopics',
        ),
        migrations.DeleteModel(
            name='HistoricalTopicVideos',
        ),
        migrations.DeleteModel(
            name='Topics',
        ),
        migrations.DeleteModel(
            name='TopicVideos',
        ),
    ]
