# Generated by Django 5.1.6 on 2026-02-23 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_delete_chaptertopics_delete_historicalchaptertopics_and_more'),
        ('instructor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='courseinstructors',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructor.instructorprofile'),
        ),
        migrations.DeleteModel(
            name='PartnerImages',
        ),
        migrations.DeleteModel(
            name='Testimonials',
        ),
        migrations.AddField(
            model_name='course',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apporved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.IntegerField(choices=[(1, 'All'), (2, 'Beginner'), (3, 'Intermediate'), (4, 'Expert')], default=1),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='level',
            field=models.IntegerField(choices=[(1, 'All'), (2, 'Beginner'), (3, 'Intermediate'), (4, 'Expert')], default=1),
        ),
        migrations.DeleteModel(
            name='InstructorProfile',
        ),
    ]
