# Generated by Django 5.1.6 on 2026-03-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterbooks',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='historicalchapterbooks',
            name='chapter',
        ),
        migrations.AddField(
            model_name='chapterbooks',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalchapterbooks',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
