# Generated by Django 5.1.6 on 2026-03-20 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_chapterbooks_chapter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetags',
            name='name',
        ),
        migrations.AddField(
            model_name='coursetags',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.tags'),
        ),
    ]
