# Generated by Django 5.1.6 on 2026-03-20 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_coursetags_name_coursetags_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterbooks',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.chapters'),
        ),
        migrations.AddField(
            model_name='historicalchapterbooks',
            name='chapter',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.chapters'),
        ),
    ]
