# Generated by Django 5.1.6 on 2026-03-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_chapterbooks_chapter_historicalchapterbooks_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='bg_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='mini_lms/images/'),
        ),
        migrations.AddField(
            model_name='categories',
            name='text_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcategories',
            name='bg_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcategories',
            name='icon',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalcategories',
            name='text_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
