# Generated by Django 5.1.6 on 2026-04-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_categories_bg_code_categories_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_duration_type',
            field=models.IntegerField(choices=[(1, 'ExtraShort'), (2, 'Short'), (3, 'Medium'), (4, 'Long'), (5, 'ExtraLong')], default=1),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='video_duration_type',
            field=models.IntegerField(choices=[(1, 'ExtraShort'), (2, 'Short'), (3, 'Medium'), (4, 'Long'), (5, 'ExtraLong')], default=1),
        ),
    ]
