# Generated by Django 5.1.6 on 2026-04-16 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_remove_chapterlectures_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcoursechapters',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='historicalcoursechapters',
            name='course',
        ),
        migrations.RemoveField(
            model_name='historicalcoursechapters',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcoursefaqs',
            name='course',
        ),
        migrations.RemoveField(
            model_name='historicalcoursefaqs',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcoursereviewrating',
            name='course',
        ),
        migrations.RemoveField(
            model_name='historicalcoursereviewrating',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcoursereviewrating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalcoursesamplevideos',
            name='course',
        ),
        migrations.RemoveField(
            model_name='historicalcoursesamplevideos',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltrailcoursechapters',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='historicaltrailcoursechapters',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltrailcoursechapters',
            name='trail_course',
        ),
        migrations.RemoveField(
            model_name='historicaltrailcourses',
            name='course',
        ),
        migrations.RemoveField(
            model_name='historicaltrailcourses',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalChapterLectures',
        ),
        migrations.DeleteModel(
            name='HistoricalCourseChapters',
        ),
        migrations.DeleteModel(
            name='HistoricalCourseFaqs',
        ),
        migrations.DeleteModel(
            name='HistoricalCourseReviewRating',
        ),
        migrations.DeleteModel(
            name='HistoricalCourseSampleVideos',
        ),
        migrations.DeleteModel(
            name='HistoricalTrailCourseChapters',
        ),
        migrations.DeleteModel(
            name='HistoricalTrailCourses',
        ),
    ]
