# Generated by Django 5.1.6 on 2026-04-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_categories_deleted_at_categories_restored_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='assessment_test_each_testlet_questions',
        ),
        migrations.RemoveField(
            model_name='course',
            name='assessment_test_testlets',
        ),
        migrations.RemoveField(
            model_name='course',
            name='mock_test_pattern',
        ),
        migrations.RemoveField(
            model_name='historicalcourse',
            name='assessment_test_each_testlet_questions',
        ),
        migrations.RemoveField(
            model_name='historicalcourse',
            name='assessment_test_testlets',
        ),
        migrations.RemoveField(
            model_name='historicalcourse',
            name='mock_test_pattern',
        ),
        migrations.AddField(
            model_name='course',
            name='no_of_mcqs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='no_of_mcqs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
