# Generated by Django 5.1.6 on 2026-05-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_remove_course_assessment_test_each_testlet_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='original_price',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='subtitle_language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='original_price',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='subtitle_language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
