# Generated by Django 5.1.6 on 2026-05-14 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_courseannouncements_announcementcomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursereviewrating',
            name='image',
        ),
        migrations.RemoveField(
            model_name='coursereviewrating',
            name='name',
        ),
    ]
