# Generated by Django 5.1.6 on 2026-05-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_remove_coursereviewrating_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereviewrating',
            name='approvad',
            field=models.IntegerField(default=0),
        ),
    ]
