# Generated by Django 5.1.6 on 2026-05-18 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_coursereviewrating_approvad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursereviewrating',
            old_name='approvad',
            new_name='approved',
        ),
    ]
