# Generated by Django 5.1.6 on 2026-06-23 05:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_rename_approvad_coursereviewrating_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage (%)'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='e.g., 10.00 for 10% or $10', max_digits=10)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('max_usages', models.PositiveIntegerField(default=1, help_text='Total times this coupon can be used globally.')),
                ('usages_count', models.PositiveIntegerField(default=0, help_text='Current global usage count.')),
                ('max_per_user', models.PositiveIntegerField(default=1, help_text='Max times a single user can redeem this code.')),
            ],
        ),
    ]
