# Generated by Django 5.1.6 on 2026-06-24 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_coupon_created_at_coupon_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='active',
            new_name='status',
        ),
    ]
