# Generated by Django 5.1.6 on 2026-06-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_rename_active_coupon_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='minimum_cart_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum total cart value required to use this coupon.', max_digits=10),
        ),
    ]
