# Generated by Django 5.1.6 on 2026-07-09 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_coupon_minimum_cart_value'),
        ('instructor', '0002_remove_instructorprofile_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinstructors',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instructor.instructorprofile'),
        ),
    ]
