# Generated by Django 5.1.6 on 2026-09-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_alter_courseinstructors_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterbooks',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='mini_lms/audio/'),
        ),
        migrations.AddField(
            model_name='historicalchapterbooks',
            name='audio_file',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
