# Generated by Django 5.1.6 on 2026-08-17 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('work_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('institution_type', models.CharField(choices=[('University/4 Year College', 'University/4 Year College'), ('2 Year College', '2 Year College'), ('Graduate or Professional School', 'Graduate or Professional School'), ('Ministry of Education', 'Ministry of Education'), ('Other', 'Other')], default='Other', max_length=50)),
                ('institution_name', models.CharField(blank=True, max_length=255, null=True)),
                ('job_role', models.CharField(choices=[('President/Provost', 'President/Provost'), ('Chancellor/Rector', 'Chancellor/Rector'), ('Vice-Chancellor/Vice-Rector', 'Vice-Chancellor/Vice-Rector'), ('Vice-President/Vice-Provost', 'Vice-President/Vice-Provost'), ('Registrar', 'Registrar'), ('CEO', 'CEO'), ('COO/CIO', 'COO/CIO'), ('Dean', 'Dean'), ('Department Head', 'Department Head'), ('Director', 'Director'), ('Professor', 'Professor'), ('Student', 'Student')], default='student', max_length=50)),
                ('department', models.CharField(choices=[('Academic Affairs', 'Academic Affairs'), ('Career Services', 'Career Services'), ('Continuing Education', 'Continuing Education'), ('Enrollment Management', 'Enrollment Management'), ('Executive Leadership', 'Executive Leadership'), ('International', 'International'), ('Strategic Planning', 'Strategic Planning'), ('Student Affairs', 'Student Affairs'), ('Teaching/Faculty/Research', 'Teaching/Faculty/Research'), ('Other', 'Other')], default='Other', max_length=100)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('approved_status', models.IntegerField(choices=[(1, 'New'), (2, 'Approved'), (3, 'Rejected')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apporved_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'University',
            },
        ),
    ]
